// NIP-52 calendar events: kind 31922 (date-based, start/end = YYYY-MM-DD)
// and 31923 (time-based, start/end = unix seconds). Addressable per author —
// unlike topics, the namespace is (pubkey, d), NOT relay-communal. Central to
// the "posting events → direct calendar sync" promise of Nodex Talk.

import { NOSTR_KINDS } from "./nostr-kinds";
import { deriveChannelTags } from "./hashtags";
import type { RawNostrEvent } from "./event-to-post";

export interface CalendarEvent {
  d: string;
  pubkey: string;
  eventId: string;
  kind: number;
  title: string;
  /** As tagged: YYYY-MM-DD for kind 31922, unix seconds for kind 31923. */
  start: string;
  end?: string;
  location?: string;
  content: string;
  channels: string[];
  relays: string[];
  createdAt: number;
}

export function isCalendarKind(kind: number): boolean {
  return kind === NOSTR_KINDS.calendarDate || kind === NOSTR_KINDS.calendarTime;
}

/** Replaceable address key: calendar events are per-author, per-d. */
export function calendarAddress(event: Pick<CalendarEvent, "pubkey" | "d">): string {
  return `${event.pubkey}:${event.d}`;
}

export function parseCalendarEvent(
  event: RawNostrEvent,
  relayIds: string[]
): CalendarEvent | null {
  const tag = (name: string) => event.tags.find((entry) => entry[0] === name && entry[1])?.[1];
  const d = tag("d");
  const start = tag("start");
  if (!d || !start) return null;
  const title = tag("title")?.trim() || event.content.split("\n")[0].trim();
  if (!title) return null;
  return {
    d,
    pubkey: event.pubkey,
    eventId: event.id,
    kind: event.kind,
    title,
    start,
    end: tag("end"),
    location: tag("location"),
    content: event.content,
    channels: deriveChannelTags(event.tags, event.content),
    relays: [...relayIds],
    createdAt: event.created_at,
  };
}

/** Composer form state for attaching a calendar event to a message. */
export interface CalendarDraft {
  title: string;
  allDay: boolean;
  /** From `<input type="date">` — YYYY-MM-DD. */
  startDate: string;
  /** From `<input type="time">` — HH:MM (ignored when allDay). */
  startTime: string;
  endDate?: string;
  endTime?: string;
  location?: string;
}

/** The wire-ready inputs a calendar event is built from (start/end encoded). */
export interface CalendarEventInput {
  title: string;
  allDay: boolean;
  /** Encoded per kind: YYYY-MM-DD (all-day) or unix-seconds string (timed). */
  start: string;
  end?: string;
  location?: string;
  content: string;
  channels: string[];
}

/**
 * Build an unsigned NIP-52 calendar event. Pure wire-encoding: kind 31922
 * (all-day, YYYY-MM-DD) or 31923 (timed, unix seconds); tags are ordered
 * d, title, start, [end], [location], then one lowercased `t` per channel. `d`
 * is generated by the caller (kept out so this stays deterministic/testable).
 */
export function buildCalendarEvent(
  input: CalendarEventInput,
  d: string
): { kind: number; content: string; tags: string[][] } {
  const kind = input.allDay ? NOSTR_KINDS.calendarDate : NOSTR_KINDS.calendarTime;
  const tags: string[][] = [
    ["d", d],
    ["title", input.title.trim()],
    ["start", input.start],
  ];
  if (input.end) tags.push(["end", input.end]);
  if (input.location) tags.push(["location", input.location]);
  for (const channel of input.channels) tags.push(["t", channel.toLowerCase()]);
  return { kind, content: input.content, tags };
}

/**
 * Encode a form draft's date/time fields into NIP-52 wire values. Timezone-
 * dependent (all-day uses the raw date, timed converts local date+time to unix
 * seconds), so this is deliberately NOT part of the deterministic build vector.
 */
export function encodeCalendarWhen(draft: CalendarDraft): { start: string; end?: string } {
  if (draft.allDay) {
    return { start: draft.startDate, end: draft.endDate || undefined };
  }
  const toUnix = (date: string, time: string) =>
    String(Math.floor(new Date(`${date}T${time || "00:00"}`).getTime() / 1000));
  const startTime = draft.startTime || "00:00";
  const end = draft.endDate
    ? toUnix(draft.endDate, draft.endTime || startTime)
    : undefined;
  return { start: toUnix(draft.startDate, startTime), end };
}

function formatDateOnly(value: string, fmt: Intl.DateTimeFormat): string {
  const [year, month, day] = value.split("-").map(Number);
  if (!year || !month || !day) return value;
  return fmt.format(new Date(year, month - 1, day));
}

/** Human-readable "when" for a calendar card (localized via Intl). */
export function formatCalendarWhen(event: CalendarEvent, locale?: string): string {
  if (event.kind === NOSTR_KINDS.calendarDate) {
    const fmt = new Intl.DateTimeFormat(locale, { dateStyle: "medium" });
    const start = formatDateOnly(event.start, fmt);
    const end = event.end ? formatDateOnly(event.end, fmt) : undefined;
    return end && end !== start ? `${start} – ${end}` : start;
  }
  const dateTime = new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" });
  const start = new Date(Number(event.start) * 1000);
  const startStr = dateTime.format(start);
  if (!event.end) return startStr;
  const end = new Date(Number(event.end) * 1000);
  const endStr =
    start.toDateString() === end.toDateString()
      ? new Intl.DateTimeFormat(locale, { timeStyle: "short" }).format(end)
      : dateTime.format(end);
  return `${startStr} – ${endStr}`;
}
